# Setup
title:        Yi Zhang's Personal Site
tagline:      Collections of my personal docs, codes, news and more.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Yi Zhang
  url:        https://yizhang-zju.github.io

# project repository
repository: https://github.com/yizhang-zju/yizhang-zju.github.io.git

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
